### ISSUE TITLE
Error at run example

### ISSUE THREAD

**Issue by milen-prg** [vlang/sdl#488]
**V version:** 
**OS:** 

V full version: V 0.3.3 6e670ec.6e1e406
OS: windows, Microsoft Windows 10 Pro v19045 64-bit
Processor: 4 cpus, 64bit, little endian,

getwd: C:\Users\mlap\Documents\m\Installs\Vlang\sdl-master\examples\tvintris
vexe: C:\v\v.exe
vexe mtime: 2023-03-17 13:09:22

vroot: OK, value: C:\v
VMODULES: OK, value: C:\Users\mlap\.vmodules
VTMP: OK, value: C:\Users\mlap\AppData\Local\Temp\v_0

Git version: git version 2.37.3.windows.1
Git vroot status: weekly.2022.40-990-g6e1e4062
.git/config present: true

CC version: Error: exec failed (CreateProcess) with code 2: The system cannot find the file specified. cmd: cc --version
thirdparty/tcc status: thirdparty-windows-amd64 1e6e7c6f

**What did you do?**

Try to run the example of sdl (after successfully v install sdl):
C:\Users\mlap\Documents\m\Installs\Vlang\sdl-master\examples\tvintris>v run .

**What did you expect to see?**

Must run visual tvintris.
 
**What did you see instead?**

INFO: compile with `v -live . `, if you want to use the [live] function draw_begin .
builder error: 'SDL.h' not found

With other examples - similar messages.

P.S. Please - write, what is this problem:

CC version: Error: exec failed (CreateProcess) with code 2: The system cannot find the file specified. cmd: cc --version

I installed v lang with its tcc, and all worked fine, I periodically successfully update all with v up and v update.

**Comment by Larpon** [comment]
Are you following the instructions for Windows in the [README.md](https://github.com/vlang/sdl#windows)?

**Comment by milen-prg** [comment]
> Are you following the instructions for Windows in the [README.md](https://github.com/vlang/sdl#windows)?

I apologize, I miss the step with copying the dll-s. Now all works! Thank you, very much!
