### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by rc4000** [vlang/sdl#490]
Is there documentation available for this project?

**Comment by Larpon** [comment]
Yes,

The [README.md](https://github.com/vlang/sdl).

You can use `v doc -m -f html ~/.vmodules/sdl` to generate html locally (it will be generated in a new folder, named `~/.vmodules/sdl/_docs/`).

And then there's of course the [official SDL2 docs](https://wiki.libsdl.org/SDL2/APIByCategory)

**Comment by rc4000** [comment]
> Yes,
> 
> The [README.md](https://github.com/vlang/sdl).
> 
> You can use `v doc -m -f html ~/.vmodules/sdl` to generate html documentation locally (it will be generated in a new folder, named `~/.vmodules/sdl/_docs/`).
> 
> And then there's of course the [official SDL2 docs](https://wiki.libsdl.org/SDL2/APIByCategory)

Thanks!
