### ISSUE TITLE
AudioCallback function missing len parameter

### ISSUE THREAD

**Issue by gjones007** [vlang/sdl#557]
In audio.c.v,  I think the documented typedef was truncated, it shows:

// This function is called when the audio device needs more data.
...
// `typedef void (SDLCALL * SDL_AudioCallback) (void *userdata, Uint8 * stream)`

from the SDL headers it is defined

typedef void (SDLCALL * SDL_AudioCallback) (void *userdata, Uint8 * stream, int len);

And so, the real issue is, the function type for AudioCallback is missing the len parameter.

pub type AudioCallback = fn (userdata voidptr, stream &u8)

to

pub type AudioCallback = fn (userdata voidptr, stream &u8, len int)

Thanks!

**Comment by Larpon** [comment]
That's a good observation. What version of SDL2 are you using with `vlang/sdl`? If you're on a Unix like system you can likely run `sdl2-config --version`. Judging from the function signature I'm guessing it might have been eaten in the translation process since `len` is a keyword 😅
