### ISSUE TITLE
Wrapper for SDL_RenderSetVSync

### ISSUE THREAD

**Issue by bru65pag** [vlang/sdl#695]
Could we get a wrapper for SDL_RenderSetVSync?

int SDL_RenderSetVSync(SDL_Renderer* renderer, int vsync) toggles the vsync of a renderer.

Thank you.

**Comment by Larpon** [comment]
> Could we get a wrapper for SDL_RenderSetVSync?
> 
> int SDL_RenderSetVSync(SDL_Renderer* renderer, int vsync) toggles the vsync of a renderer.
> 
> Thank you.

Hi @bru65pag!

`SDL_RenderSetVSync` is available via `sdl.render_set_v_sync(renderer &Renderer, vsync int)` from SDL version >=  2.0.18
So you'll have to use a SDL version >= 2.0.18 as any older versions did not implement that function.

See also official SDL doc comment in the 2.0.18 branch: https://github.com/vlang/sdl/blob/2f4d74d7ae76e04fa4a55b608cd8a1de53c14d10/render.c.v#L1878
