### ISSUE TITLE
Basic window example returns C error

### ISSUE THREAD

**Issue by MedLabs** [vlang/sdl#741]
**V version:** 
v 0.4.4 aeadc0a

**OS:** 
Arcolinux 24.04.02 on KDE Plasma 6.0.1

**What did you do?**
``` v new try_sdl```
then copied the basic window main.v
then  ```v install sdl```
and ``` v run .```

**What did you expect to see?**
a basic window
 
**What did you see instead?**
```
 las@lapsus  /backup/dev/v/scratchpad/try_sdl  v run .
==================
/tmp/v_1000/try_sdl.01HRWH9GNEA7V1BBTFE30QR0SK.tmp.c:1993: error: ';' expected (got "sdl__OSEvent")
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

**Comment by Larpon** [comment]
You need to make sure the version of SDL2 installed on your system matches the major and minor version branch from this repository.

What is the SDL2 version installed on your system?

**Comment by MedLabs** [comment]
sdl2-2.30.1-1

**Comment by Larpon** [comment]
In that case you'll need to follow the [install instructions](https://github.com/vlang/sdl/tree/master?tab=readme-ov-file#install) below the line containing `v install sdl`.

It basically:
```bash
git clone https://github.com/vlang/sdl.git ~/.vmodules/sdl
v ~/.vmodules/sdl/setup.vsh
```
Or, if that fails
```bash
git clone https://github.com/vlang/sdl.git ~/.vmodules/sdl
cd ~/.vmodules/sdl
git checkout 2.30.0
```

**Comment by MedLabs** [comment]
there is no branch for 2.31.0 ?

**Comment by JalonSolov** [comment]
You said you have 2.30.1, so... why?

At any rate, no, there is no branch for 2.31, yet.  Each new branch has to be manually created, taking into account the differences in the new version of sdl, etc.  It doesn't happen automatically.
